### ISSUE TITLE
Migrate to a newer sequelize version

### ISSUE THREAD

**Issue by jlescot** [AirVantage/node-tech-db#3]
We are currently using v2.0.6 but during the `npm install` on _app-metrics_, I got the following message in the console:
`npm WARN deprecated sequelize@2.0.6: critical security fix in v3.0.0`

So we really need to migrate to a newer version of sequelize, but this will require lots of changes on _app-accounts_ and _app-metrics_ side

**Comment by phtrivier** [comment]
To be started once express 4 migration is merged... 
However, why would it affect app-ui ? We don't have mysql in app-ui, do we ?

**Comment by jlescot** [comment]
No you're right, I updated my previous comment. And yes, we will wait first the migration to express 4

**Comment by jlescot** [comment]
Closing this issue since migration is done as part of https://github.com/AirVantage/node-tech-db/pull/4 for this component.

So next step is to update the dependency on `av-accounts` / `av-metrics` side
